/// Flutter icons Emotion
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Emotion
///      fonts:
///       - asset: fonts/Emotion.ttf
///
/// 
/// * Fontelico, Copyright (C) 2012 by Fontello project
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://fontello.com
///
import 'package:flutter/widgets.dart';

class Emotion {
  Emotion._();

  static const _kFontFam = 'Emotion';

  static const IconData emo_happy = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData emo_thumbsup = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData emo_surprised = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData emo_tongue = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData emo_displeased = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData emo_angry = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData emo_cry = const IconData(0xe80f, fontFamily: _kFontFam);
}
